    const deck= [
      "Wonyoung ⭐\nPosition: Visual\nInfluence: 80k fans",
      "Wonyoung ⭐⭐\nPosition: Visual\nInfluence: 150k fans",
      "Wonyoung ⭐⭐⭐\nPosition: Visual\nInfluence: 250k fans",
      "Rei ⭐\nPosition: Rapper\nInfluence: 60k fans",
      "Rei ⭐⭐\nPosition: Rapper\nInfluence: 120k fans",
      "Rei ⭐⭐⭐\nPosition: Rapper\nInfluence: 220k fans",
      "Liz ⭐\nPosition: Vocal\nInfluence: 60k fans",
      "Liz ⭐⭐\nPosition: Vocal\nInfluence: 130k fans",
      "Liz ⭐⭐⭐\nPosition: Vocal\nInfluence: 230k fans",
      "Yujin ⭐\nPosition: Dance\nInfluence: 70k fans",
      "Yujin ⭐⭐\nPosition: Dance\nInfluence: 140k fans",
      "Yujin ⭐⭐⭐\nPosition: Dance\nInfluence: 240k fans",
      "Jennie ⭐\nPosition: Rapper\nInfluence: 80k fans",
      "Jennie ⭐⭐\nPosition: Rapper\nInfluence: 150k fans",
      "Jennie ⭐⭐⭐\nPosition: Rapper\nInfluence: 250k fans",
      "Rosé ⭐\nPosition: Vocal\nInfluence: 70k fans",
      "Rosé ⭐⭐\nPosition: Vocal\nInfluence: 130k fans",
      "Rosé ⭐⭐⭐\nPosition: Vocal\nInfluence: 240k fans",
      "Lisa ⭐\nPosition: Dance\nInfluence: 80k fans",
      "Lisa ⭐⭐\nPosition: Dance\nInfluence: 150k fans",
      "Lisa ⭐⭐⭐\nPosition: Dance\nInfluence: 250k fans",
      "Jisoo ⭐\nPosition: Visual\nInfluence: 70k fans",
      "Jisoo ⭐⭐\nPosition: Visual\nInfluence: 120k fans",
      "Jisoo ⭐⭐⭐\nPosition: Visual\nInfluence: 230k fans",
      "Karina ⭐\nPosition: Visual/Dance\nInfluence: 70k fans",
      "Karina ⭐⭐\nPosition: Visual/Dance\nInfluence: 130k fans",
      "Karina ⭐⭐⭐\nPosition: Visual/Dance\nInfluence: 250k fans",
      "Winter ⭐\nPosition: Vocal\nInfluence: 60k fans",
      "Winter ⭐⭐\nPosition: Vocal\nInfluence: 140k fans",
      "Winter ⭐⭐⭐\nPosition: Vocal\nInfluence: 240k fans",
      "Ningning ⭐\nPosition: Vocal\nInfluence: 60k fans",
      "Ningning ⭐⭐\nPosition: Vocal\nInfluence: 130k fans",
      "Ningning ⭐⭐⭐\nPosition: Vocal\nInfluence: 230k fans",
      "Giselle ⭐\nPosition: Rapper\nInfluence: 60k fans",
      "Giselle ⭐⭐\nPosition: Rapper\nInfluence: 120k fans",
      "Giselle ⭐⭐⭐\nPosition: Rapper\nInfluence: 220k fans",
      "Chaewon ⭐\nPosition: Dance\nInfluence: 80k fans",
      "Chaewon ⭐⭐\nPosition: Dance\nInfluence: 150k fans",
      "Chaewon ⭐⭐⭐\nPosition: Dance\nInfluence: 250k fans",
      "Kazuha ⭐\nPosition: Visual\nInfluence: 70k fans",
      "Kazuha ⭐⭐\nPosition: Visual\nInfluence: 140k fans",
      "Kazuha ⭐⭐⭐\nPosition: Visual\nInfluence: 230k fans",
      "Sakura ⭐\nPosition: Rapper\nInfluence: 70k fans",
      "Sakura ⭐⭐\nPosition: Rapper\nInfluence: 130k fans",
      "Sakura ⭐⭐⭐\nPosition: Rapper\nInfluence: 230k fans",
      "Yunjin ⭐\nPosition: Vocal\nInfluence: 70k fans",
      "Yunjin ⭐⭐\nPosition: Vocal\nInfluence: 130k fans",
      "Yunjin ⭐⭐⭐\nPosition: Vocal\nInfluence: 230k fans",
      "Jihyo ⭐\nPosition: Vocal\nInfluence: 70k fans",
      "Jihyo ⭐⭐\nPosition: Vocal\nInfluence: 130k fans",
      "Jihyo ⭐⭐⭐\nPosition: Vocal\nInfluence: 230k fans",
      "Momo ⭐\nPosition: Dance\nInfluence: 80k fans",
      "Momo ⭐⭐\nPosition: Dance\nInfluence: 140k fans",
      "Momo ⭐⭐⭐\nPosition: Dance\nInfluence: 240k fans",
      "Chaeyoung ⭐\nPosition: Rap\nInfluence: 60k fans",
      "Chaeyoung ⭐⭐\nPosition: Rap\nInfluence: 120k fans",
      "Chaeyoung ⭐⭐⭐\nPosition: Rap\nInfluence: 220k fans",
      "Tzuyu ⭐\nPosition: Visual\nInfluence: 80k fans",
      "Tzuyu ⭐⭐\nPosition: Visual\nInfluence: 150k fans",
      "Tzuyu ⭐⭐⭐\nPosition: Visual\nInfluence: 250k fans",
      "Yuna ⭐\nPosition: Visual\nInfluence: 70k fans",
      "Yuna ⭐⭐\nPosition: Visual\nInfluence: 130k fans",
      "Yuna ⭐⭐⭐\nPosition: Visual\nInfluence: 230k fans",
      "Ryujin ⭐\nPosition: Rap\nInfluence: 70k fans",
      "Ryujin ⭐⭐\nPosition: Rap\nInfluence: 140k fans",
      "Ryujin ⭐⭐⭐\nPosition: Rap\nInfluence: 240k fans",
      "Lia ⭐\nPosition: Vocal\nInfluence: 70k fans",
      "Lia ⭐⭐\nPosition: Vocal\nInfluence: 130k fans",
      "Lia ⭐⭐⭐\nPosition: Vocal\nInfluence: 230k fans",
      "Yeji ⭐\nPosition: Dance\nInfluence: 80k fans",
      "Yeji ⭐⭐\nPosition: Dance\nInfluence: 150k fans",
      "Yeji ⭐⭐⭐\nPosition: Dance\nInfluence: 250k fans"
    ];

const supportDeck = [
  "Training vocals\nType: Training\n+10k IP",
  "Training dance\nType: Training\n+10k IP",
  "Training rap\nType: Training\n+10k IP",

  "Ambassador\nType: Promotion (only on ⭐⭐⭐)\n+50k IP",
  "Variety show\nType: Promotion (only on ⭐⭐ or higher)\n+30k IP",
  "Interview\nType: Promotion (only on ⭐)\n+20k IP",
  "Live broadcast\nType: Promotion\n+20k IP",
  "Survival show\nType: Promotion (only on ⭐)\n+50k IP",
  "Viral TikTok\nType: Promotion\n+10k IP",
  "Hip pads\nType: Promotion\n+10k IP",
  "Plastic surgery\nType: Promotion\n+30k IP",

  "Investment\nType: Draw\nDraw 3 cards",
  "Scout\nType: Draw\nTop 4 cards, choose 2",
  "Recruit\nType: Draw\nSearch your deck for any card",

  "Bully scandal\nType: Sabotage\nRemove member from stage (⭐ or ⭐⭐ only)",
  "Drug allegations\nType: Sabotage\n-50k IP",
  "Dating scandal\nType: Sabotage\n-30k IP",
  "Hip pad allegation\nType: Sabotage\n-20k IP",
  "Plastic surgery allegations\nType: Sabotage\n-40k IP",

  "YG\nType: Entertainment Company\nBLACKPINK MEMBERS +30k EACH",
  "JYP\nType: Entertainment Company\nTWICE AND ITZY MEMBERS +20k EACH",
  "STARSHIP\nType: Entertainment Company\nWONYOUNG +50k, IVE MEMBERS +20k EACH",
  "SM\nType: Entertainment Company\nAESPA MEMBERS +20k EACH",
  "HYBE (SOURCE MUSIC)\nType: Entertainment Company\nLESSERAFIM MEMBERS +20k EACH",

  "ELEVEN\nType: Song\nIVE MEMBERS +10k EACH",
  "DALLA DALLA\nType: Song\nITZY MEMBERS +10k EACH",
  "LIKE OOH AHH\nType: Song\nTWICE MEMBERS +10k EACH",
  "BOOMBAYAH\nType: Song\nBLACKPINK MEMBERS +10k EACH",
  "BLACK MAMBA\nType: Song\nAESPA MEMBERS +10k EACH",
  "FEARLESS\nType: Song\nLESSERAFIM MEMBERS +10k EACH (only 1 per member counted)"
];



